language: ruby
rvm:
  - "2.1.3"
services:
  - mongodb
after_success:
  - "echo $DEPLOY_KEY"
  - "openssl aes-256-cbc -k \"$DEPLOY_KEY\" -in config/deploy_id_rsa_enc -d -a -out config/deploy_id_rsa"
  - "[[ $TRAVIS_BRANCH = 'master' ]] && bundle exec cap production deploy"
env:
  global:
    secure: SAzupk2wxtdpDjSwIVftZS06qq7ssq1rupZOvPa0yHTylI+NiMXO5uwKGbHUDIrH3MzvriwJKW7LrahDJIRMTzQvv7cIYSlSdW8s4K66AXTrx1wy6w1APk72QTsgMJEsMfuIjWmdQSpCJdESFK5ONzf5E62yz2+q6z+cvAJ1THY=
