# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad1bce3d5c33aa1fae632526e2749821bf987b433285976db0801ab91998ce8f83872dfb43bd2bb300243ce1a0caa3ede0eaca8abc9403f062b55e1399af5fd9

test:
  secret_key_base: 39bc6b7f7afa4babe9268203cf6b9dc629345715fd1c5dd3b47d4dac7737140a6495ea9db578c93cdc9cd1d206ac9a37d91c404e9ebf204a759588445a907747

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
